location_plot <- function(gam, species_subset) {
  jet.colors = colorRampPalette(rev(c("#042333b2",
                                      "#0c2a50b2",
                                      "#13306db2",
                                      "#253582b2",
                                      "#403891b2",
                                      "#593d9cb2",
                                      "#6b4596b2",
                                      "#7e4e90b2",
                                      "#a65c85b2",
                                      "#b8627db2",
                                      "#cc6a70b2",
                                      "#de7065b2",
                                      "#eb8055b2",
                                      "#f68f46b2",
                                      "#f9a242b2",
                                      "#f9b641b2",
                                      "#f7cb44b2",
                                      "#efe350b2",
                                      "#e8fa5bb2")))
  myvis_gam(
    gam[[2]],
    view = c('lon', 'lat'),
    too.far = 0.03,
    plot.type = 'contour',
    contour.col = contour_col,
    color = "jet" ,
    type = 'response',
    xlim = c(-176.5, -156.5),
    ylim = c(52, 62),
    family = "serif",
    xlab = "Longitude",
    ylab = "Latitude",
    main = " ",
    cex.lab = 6.5,
    cex.axis = 6.5)
  maps::map('worldHires',
            add = T,
            col = 'antiquewhite4',
            fill = T)
}
