map_vc_presentation <- function(data, gam, grids, title){
  nlat = 80
  nlon = 120
  latd = seq(min(data$lat), max(data$lat), length.out = nlat)
  lond = seq(min(data$lon), max(data$lon), length.out = nlon)
  myvis_gam(gam,
            view = c('lon', 'lat'),
            too.far = 0.04,
            plot.type = 'contour',
            contour.col = contour_col,
            color = "jet",
            type = 'link',
            xlim = c(-176.5, -156.5),
            ylim = c(52, 62),
            xlab = "",
            ylab = "",
            main = "",
            axes = FALSE)
  rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4], col = "mintcream")
  par(new = TRUE)
  myvis_gam(gam,
            view = c('lon', 'lat'),
            too.far = 0.04,
            plot.type = 'contour',
            contour.col = contour_col,
            color = "jet" ,
            type = 'link',
            xlim = c(-176.5, -156.5),
            ylim = c(52, 62),
            family = "serif",
            xlab = "Longitude",
            ylab = "Latitude",
            main = title,
            cex.main = 1.5,
            cex.lab = 1.5,
            cex.axis = 1.5)
  maps::map('worldHires',
            add = T,
            col = 'wheat4',
            fill = T)
  image.plot(legend.only = T,
             col = jet.colors(100),
             legend.shrink = 0.2,
             smallplot = c(.7, .73, .24, .38),
             legend.cex = 0.7,
             axis.args = list(cex.axis = 0.9),
             legend.width = 0.8,
             legend.mar = 6,
             zlim = c(0, 26000),
             legend.args = list("Abundance",
                                side = 2, cex = 0.8))
  my_color <- colorRampPalette(rev(brewer.pal(11, "RdBu")))
  image(lond,
        latd,
        t(matrix(grids[[1]]$diff,
                 nrow = length(latd),
                 ncol = length(lond),
                 byrow = T)),
        xlim = c(-176.5, -156.5),
        ylim = c(52, 62),
        axes = FALSE,
        xlab = "",
        ylab = "")
  rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4], col = "mintcream")
  par(new = TRUE)
  image(lond,
        latd,
        t(matrix(grids[[1]]$diff,
                 nrow = length(latd),
                 ncol = length(lond),
                 byrow = T)),
        col = my_color(100),
        xlab = "Longitude",
        ylab = "Latitude",
        xlim = c(-176.5, -156.5),
        ylim = c(52, 62),
        main = 'Change in distribution',
        cex.main = 1.5,
        cex.lab = 1.5,
        cex.axis = 1.5,
        zlim = c(0, 1656))
  maps::map("worldHires",
            fill = T,
            col = "wheat4",
            add = T)
  image.plot(legend.only = T,
             col = my_color(100),
             legend.shrink = 0.2,
             smallplot = c(.7, .73, .24, .38),
             legend.cex = 0.7,
             axis.args = list(cex.axis = 0.9),
             legend.width = 0.8,
             legend.mar = 6,
             zlim = c(0, 1656),
             legend.args = list("Predicted \n Change",
                                side = 2, cex = 0.8))
  plot(grids[[2]]$doy,
       grids[[2]]$pred_comb,
       main = 'Change in phenology',
       type = 'l',
       ylim = range(c(grids[[2]]$pred_up1,
                      grids[[2]]$pred_up2,
                      grids[[2]]$pred_lw1,
                      grids[[2]]$pred_lw2), na.rm = T),
       xlim = c(min(grids[[2]]$doy, na.rm = T), 
                max(grids[[2]]$doy, na.rm = T)),
       col = '#000000',
       lwd = 2,
       xlab = 'Day of the year',
       ylab = 'Egg density ln(n/10m2)',
       cex.lab = 1.5,
       cex.axis = 1.5,
       cex.main = 1.5)
  polygon(c(grids[[2]]$doy, rev(grids[[2]]$doy)),
          c(grids[[2]]$pred_lw1, rev(grids[[2]]$pred_up1)),
          col = alpha('#000000', 0.2), 
          lty = 0)
  lines(grids[[2]]$doy,
        grids[[2]]$pred_comb2,
        col = '#E69F00',
        lwd = 2)
  polygon(c(grids[[2]]$doy, rev(grids[[2]]$doy)),
          c(grids[[2]]$pred_lw2, rev(grids[[2]]$pred_up2)),
          col = alpha('#E69F00', 0.2),
          lty = 0)
}
